config/routes.rb
Qacasts::Application.routes.draw do

  root :to => 'home#index'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :wizards, :only => [:show]

  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  resources :users, :only => [:show]
  resource :user, :only => [] do
    get 'profile'
    resources :follows, :only => [:delete] do
      get 'star', :on => :member
      get 'unstar', :on => :member
      get 'follow', :on => :member
      get 'unfollow', :on => :member
      get 'stars', :on => :collection
      get 'follows', :on => :collection
    end
  end

  resources :positions, :only => [:index, :show]
  resources :articles, :only => [:index, :show] do
    get 'mine', :on => :collection
  end

  match '/:controller(/:action(/:param))'

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#change_rejected'
  match '/500', :to => 'errors#something_wrong'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_and_belongs_to_many :points
  has_and_belongs_to_many :tags
  has_one :article_content
  attr_accessible :url, :desc, :level, :name, :point_ids, :tag_ids, :user_id, :category_id
  validates :name, :presence => true, :length => {:maximum => 12}, :allow_blank => false
  validates :desc, :presence => true, :length => {:maximum => 80}, :allow_blank => false
  validates :url, :presence => true, :length => {:maximum => 256}, :allow_blank => false
  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates :level, :presence => true, :numericality => {:only_integer => true}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :auth_user

  def index
    @articles = Article.all
    @categories = Category.all
    @flash = flash[:errors]
  end

  def show
    @article = Article.find(params[:id])
  end

  def category
    @articles = Article.where(:category_id => params[:param])
    @categories = Category.all
  end

  def mine
    @articles = Article.where(:user_id => current_user.id)
    @categories = Category.all
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render 'articles/articles_nav' %>
    <div class="span9">
      <dl>
        <%- if not @articles.empty? %>
            <%- @articles.each do |a| %>
                <dt>
                  <%- if a.article_content.nil? %>
                      <%= link_to a.name, a.url, :target => :blank, :class => 'inline' %>
                  <%- else %>
                      <%= link_to a.name, a, :class => 'inline' %>
                  <%- end %>
                  <%- if current_user.star?(a.id) %>
                      <%= link_to content_tag(:i, ' ', :class => 'icon-star-empty'), star_user_follow_path(a.id), :title => t('article.star') %>
                  <%- else %>
                      <%= link_to content_tag(:i, ' ', :class => 'icon-star'), unstar_user_follow_path(a.id), :title => t('article.unstar') %>
                  <%- end %>
                </dt>
                <dd>
                  <small class="muted"><%= a.desc %></small>
                  <br/>
                  <small class="muted pull-right"><%= t('article.shared_by', :user => a.user.name) %>
                    <%- if current_user.follow?(a.user.id) %>
                        <%= link_to content_tag(:i, ' ', :class => 'icon-eye-open'), follow_user_follow_path(a.user.id), :title => t('user.follow') %>
                    <%- else %>
                        <%= link_to content_tag(:i, ' ', :class => 'icon-eye-close'), unfollow_user_follow_path(a.user.id), :title => t('user.unfollow') %>
                    <%- end %>
                  </small>
                  <br/>
                </dd>
            <%- end %>
            </dl>
        <%- else %>
            <div class="well well-large">
              <p class='lead muted text-center'>
                <%= t('article.no_articles') %>
              </p>
            </div>
        <%- end %>
        </div>
  </div>
</div>

app/views/articles/_articles_nav.html.erb
<div class="span3">
  <ul class="nav nav-stacked nav-tabs">
    <li class="nav-header"><%= t('activerecord.models.user') %></li>
    <li class="<%= 'active' if params[:action] == 'index' %>"><%= link_to content_tag(:i, ' ', :class => 'icon-caret-right')+t('article.latest')+t('activerecord.models.article'), articles_path %></li>
    <li class="<%= 'active' if params[:action] == 'mine' %>"><%= link_to content_tag(:i, ' ', :class => 'icon-caret-right')+t('mine')+t('activerecord.models.article'), mine_articles_path %></li>
    <li class="<%= 'active' if params[:action] == 'stars' %>"><%= link_to content_tag(:i, ' ', :class => 'icon-caret-right')+t('article.star')+t('de')+t('activerecord.models.article'), stars_user_follows_path %></li>
    <li class="<%= 'active' if params[:action] == 'follows' %>"><%= link_to content_tag(:i, ' ', :class => 'icon-caret-right')+t('user.follow')+t('de')+t('activerecord.models.user'), follows_user_follows_path %></li>
    <li class="nav-header"><%= t('activerecord.models.category') %></li>
    <%- @categories.each do |c| %>
        <li class="<%= 'active' if params[:action] == 'category' && params[:param] == c.id.to_s %>"><%= link_to content_tag(:i, ' ', :class => 'icon-caret-right')+c.name, {:controller => 'articles', :action => 'category', :param => c.id} %></li>
    <%- end %>
  </ul>
</div>

app/views/articles/category.html.erb
<%= render 'articles' %>

app/views/articles/index.html.erb
<%= render 'articles' %>

app/views/articles/mine.html.erb
<%= render 'articles' %>

app/views/articles/show.html.erb
<div class="hero-unit">
  <div class="well  text-center"><h2><%= @article.name %></h2></div>
  <div class="well bg-color-f5">
    <p>
      <%= raw(@article.article_content.content) %>
    </p>
  </div>
</div>
<%= render 'disqus/comments' %>

app/views/articles/star.html.erb
<%= render 'articles' %>