config/routes.rb
Qacasts::Application.routes.draw do

  root :to => 'home#index'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :wizards, :only => [:show]

  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'}
  resources :users, :only => [:show]
  resource :user, :only => [] do
    get 'profile'
    resources :follows, :only => [:delete] do
      get 'star', :on => :member
      get 'unstar', :on => :member
      get 'follow', :on => :member
      get 'unfollow', :on => :member
      get 'stars', :on => :collection
      get 'follows', :on => :collection
    end
  end

  resources :positions, :only => [:index, :show]
  resources :articles, :only => [:index, :show] do
    get 'mine', :on => :collection
  end

  match '/:controller(/:action(/:param))'

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#change_rejected'
  match '/500', :to => 'errors#something_wrong'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_and_belongs_to_many :points
  has_and_belongs_to_many :tags
  has_one :article_content
  attr_accessible :url, :desc, :level, :name, :point_ids, :tag_ids, :user_id, :category_id
  validates :name, :presence => true, :length => {:maximum => 12}, :allow_blank => false
  validates :desc, :presence => true, :length => {:maximum => 80}, :allow_blank => false
  validates :url, :presence => true, :length => {:maximum => 256}, :allow_blank => false
  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates :level, :presence => true, :numericality => {:only_integer => true}
end

app/models/article_content.rb
class ArticleContent < ActiveRecord::Base
  belongs_to :article
  attr_accessible :content, :article_id
  validates :content, :presence => true, :allow_blank => false
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :length => {:maximum => 8}, :allow_blank => false
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :follow_id, :scope => [:user_id, :follow_type]
  attr_accessible :follow_id, :follow_type, :user_id
end

app/models/point.rb
class Point < ActiveRecord::Base
  attr_accessible :desc, :name, :position_ids, :article_ids
  has_and_belongs_to_many :positions
  has_and_belongs_to_many :articles
  validates :name, :presence => true, :length => {:maximum => 12}, :allow_blank => false
  validates :desc, :presence => true, :length => {:maximum => 80}, :allow_blank => false
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :desc, :name, :point_ids
  has_and_belongs_to_many :points
  validates :name, :presence => true, :length => {:maximum => 12}, :allow_blank => false
  validates :desc, :presence => true, :length => {:maximum => 80}, :allow_blank => false
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :article_ids
  has_and_belongs_to_many :articles
  validates :name, :presence => true, :length => {:maximum => 8}, :allow_blank => false
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  #:lockable, :timeoutable, :omniauthable : recoverable, :rememberable, :trackable, :validatable, :registerable, :rememberable, :database_authenticatable,
  devise :database_authenticatable, :omniauthable, :omniauth_providers => [:google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :article_ids
  has_many :articles
  has_many :follows

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(name: data["name"],
                         email: data["email"],
                         password: Devise.friendly_token[0, 20],
                         provider: 'Google',
                         uid: data["name"]
      )
    end
    user
  end

  def star?(article_id)
    Follow.where(:user_id => self.id, :follow_id => article_id, :follow_type => :article).empty?
  end

  def follow?(user_id)
    Follow.where(:user_id => self.id, :follow_id => user_id, :follow_type => :user).empty?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :auth_user

  def index
    @articles = Article.all
    @categories = Category.all
    @flash = flash[:errors]
  end

  def show
    @article = Article.find(params[:id])
  end

  def category
    @articles = Article.where(:category_id => params[:param])
    @categories = Category.all
  end

  def mine
    @articles = Article.where(:user_id => current_user.id)
    @categories = Category.all
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found

  end

  def change_rejected

  end

  def something_wrong

  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def star
    @article = Article.find(params[:id])
    @star=current_user.follows.build(:follow_id => params[:id], :follow_type => :article)
    if @star.save
      redirect_to articles_path, :flash => {:notice => t('article.star_successfully', :article => @article.name)}
    else
      redirect_to articles_path, :flash => {:errors => @star}
    end
  end

  def unstar
    @article = Article.find(params[:id])
    @unstar=Follow.where(:user_id => current_user.id, :follow_id => params[:id], :follow_type => :article).first
    if @unstar.delete
      redirect_to articles_path, :flash => {:notice => t('article.unstar_successfully', :article => @article.name)}
    else
      redirect_to articles_path, :flash => {:errors => @star}
    end
  end

  def stars
    @articles_id = Follow.where(:user_id => current_user.id, :follow_type => :article).map(&:follow_id)
    @articles = Article.where('id in (?)', @articles_id)
    @categories = Category.all
  end

  def follow
    @user = User.find(params[:id])
    @follow=current_user.follows.build(:follow_id => params[:id], :follow_type => :user)
    if @follow.save
      redirect_to articles_path, :flash => {:notice => t('user.follow_successfully', :user => @user.name)}
    else
      redirect_to articles_path, :flash => {:errors => @follow}
    end
  end

  def unfollow
    @user = User.find(params[:id])
    @unfollow=Follow.where(:user_id => current_user.id, :follow_id => params[:id], :follow_type => :user).first
    if @unfollow.delete
      redirect_to articles_path, :flash => {:notice => t('user.unfollow_successfully', :user => @user.name)}
    else
      redirect_to articles_path, :flash => {:errors => @unfollow}
    end
  end

  def follows
    @users_id = Follow.where(:user_id => current_user.id, :follow_type => :user).map(&:follow_id)
    @users = User.where('id in (?)', @users_id)
    @categories = Category.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :auth_user

  def index

  end
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_filter :auth_user, :except => [:show]

  include Wicked::Wizard
  steps :first, :second, :third

  def show
    @user = current_user
    case step
      when 'wicked_finish'
        @user.update_attribute(:wizard, true)
    end
    render_wizard
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/disqus/_comments.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'qacasts'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

app/views/disqus/_counts.html.erb
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'qacasts'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
    

app/views/layouts/_back_to_top.html.erb
<a id="gotop" href="#">
  <span><i class="icon-arrow-up"></i></span>
</a>
<script type="text/javascript" charset="utf-8">
    $(function () {
        $(window).scroll(function () {
            var scrollt = document.documentElement.scrollTop + document.body.scrollTop;
            if (scrollt > 200) {
                $("#gotop").fadeIn(400);
            } else {
                $("#gotop").stop().fadeOut(400);
            }
        });
        $("#gotop").click(function () {
            $("html,body").animate({scrollTop: "0px"}, 200);
        });
    });
</script>
<style type="text/css">
    #gotop {
        display: block;
        width: 50px;
        height: 50px;
        position: fixed;
        bottom: 50px;
        right: 40px;
        border-radius: 10px 10px 10px 10px;
        text-decoration: none;
        display: none;
        background-color: #999999;
    }

    #gotop span {
        display: block;
        width: 50px;
        color: #dddddd;
    }

    #gotop span:hover {
        color: #cccccc;
    }

    #gotop span {
        font-size: 40px;
        text-align: center;
        margin-top: 4px;
    }
</style>

app/views/layouts/_bottom.html.erb
<hr>
<div class="container" align="center">
  <small class="muted">
    <%= raw('<site-copyright>'+t('copy_right')+'</site-copyright') %>
    <br/><br/>
  </small>
</div>

app/views/layouts/_flash.html.erb
<% if not @flash.nil? and @flash.errors.any? %>
    <% @flash.errors.full_messages.each do |msg| %>
        <script type="text/javascript">
            $(function () {
                $.pnotify({
                    text: '<%= msg %>',
                    sticker: false,
                    history: false,
                    animation: 'show',
                    nonblock: true,
                    type: 'error'
                });
            });
        </script>
    <% end %>
<% end %>

app/views/layouts/_msg.html.erb
<script type="text/javascript">
    <%if not notice.nil?%>
    $(function () {
        $.pnotify({
            text: '<%= notice %>',
            sticker: false,
            history: false,
            animation: 'show',
            nonblock: true,
            type: 'success'
        });
    });
    <%end%>
    <%if not alert.nil?%>
    $(function () {
        $.pnotify({
            text: '<%= alert %>',
            sticker: false,
            history: false,
            animation: 'show',
            nonblock: true,
            type: 'error'
        });
    });
    <%end%>
</script>

app/views/layouts/_top.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to raw('<color-title>'+t('qa')+'</color-title> <site-title>'+t('casts')+'</site-title>'), root_path, :class => 'brand' %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="<%= 'active' if params[:controller] == 'home' %>">
            <%= link_to t('home_page'), root_path %>
          </li>
          <li class="<%= 'active' if params[:controller] == 'positions' %>">
            <%= link_to t('activerecord.models.position'), positions_path %>
          </li>
          <li class="<%= 'active' if params[:controller] == 'articles' ||(params[:controller] == 'follows') %>">
            <%= link_to t('activerecord.models.article'), articles_path %>
          </li>
          <%- if user_signed_in? %>
              <li>
                <%= link_to t('site_admin'), rails_admin_path %>
              </li>
          <%- end %>
        </ul>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
              <strong><%= link_to current_user.name, root_path %></strong>
              <%= link_to content_tag(:i, ' ', :class => 'icon-signout'), destroy_user_session_path, :method => :delete, :data => {:confirm => t('are_you_sure')}, :title => t('devise.navigation.sign_out') %>
          <% else %>
              <%= link_to content_tag(:i, ' ', :class => 'icon-google-plus')+t('sign_in_with', :provider => :Google), user_omniauth_authorize_path(:google_oauth2) %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('site_name') %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lily+Script+One' rel='stylesheet' type='text/css'>
</head>
<body>
<div class='container'>
  <%= render 'layouts/top' %>
  <div class="container-fluid well">
    <%= render 'layouts/flash' %>
    <%= render 'layouts/msg' %>
    <%= yield %>
    <br/>
    <br/>
  </div>
</div>
<%= render 'layouts/bottom' %>
<%= render 'layouts/back_to_top' %>
</body>
</html>